os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"          ; fi
script:
  # Fetch
  - swift package fetch
  - rm -rf Sources/Vapor/Generator
  # Build Vapor
  - swift build --configuration debug
  - swift build --configuration release
  # Test Vapor
  - swift test
